// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TwentyQ.Data;

#nullable disable

namespace TwentyQ.Migrations
{
    [DbContext(typeof(TwentyQContext))]
    [Migration("20260127202854_1stMigration")]
    partial class _1stMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TwentyQ.Entities.AnimalAnswerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("AnimalAnswers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnimalId = 1,
                            QuestionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 2,
                            AnimalId = 1,
                            QuestionId = 2,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 3,
                            AnimalId = 1,
                            QuestionId = 3,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 4,
                            AnimalId = 1,
                            QuestionId = 4,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 5,
                            AnimalId = 2,
                            QuestionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 6,
                            AnimalId = 2,
                            QuestionId = 2,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 7,
                            AnimalId = 2,
                            QuestionId = 3,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 8,
                            AnimalId = 2,
                            QuestionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 9,
                            AnimalId = 3,
                            QuestionId = 1,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 10,
                            AnimalId = 3,
                            QuestionId = 2,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 11,
                            AnimalId = 3,
                            QuestionId = 3,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 12,
                            AnimalId = 3,
                            QuestionId = 4,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 13,
                            AnimalId = 4,
                            QuestionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 14,
                            AnimalId = 4,
                            QuestionId = 2,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 15,
                            AnimalId = 4,
                            QuestionId = 3,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 16,
                            AnimalId = 4,
                            QuestionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 17,
                            AnimalId = 5,
                            QuestionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 18,
                            AnimalId = 5,
                            QuestionId = 2,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 19,
                            AnimalId = 5,
                            QuestionId = 3,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 20,
                            AnimalId = 5,
                            QuestionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 21,
                            AnimalId = 6,
                            QuestionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 22,
                            AnimalId = 6,
                            QuestionId = 2,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 23,
                            AnimalId = 6,
                            QuestionId = 3,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 24,
                            AnimalId = 6,
                            QuestionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 25,
                            AnimalId = 7,
                            QuestionId = 1,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 26,
                            AnimalId = 7,
                            QuestionId = 2,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 27,
                            AnimalId = 7,
                            QuestionId = 3,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 28,
                            AnimalId = 7,
                            QuestionId = 4,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 29,
                            AnimalId = 8,
                            QuestionId = 1,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 30,
                            AnimalId = 8,
                            QuestionId = 2,
                            Value = 2.0
                        },
                        new
                        {
                            Id = 31,
                            AnimalId = 8,
                            QuestionId = 3,
                            Value = 0.0
                        },
                        new
                        {
                            Id = 32,
                            AnimalId = 8,
                            QuestionId = 4,
                            Value = 0.0
                        });
                });

            modelBuilder.Entity("TwentyQ.Entities.AnimalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Penguin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dog"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eagle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shark"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Cat"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Whale"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bat"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Salmon"
                        });
                });

            modelBuilder.Entity("TwentyQ.Entities.QuestionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "Does it fly?"
                        },
                        new
                        {
                            Id = 2,
                            Text = "Does it swim?"
                        },
                        new
                        {
                            Id = 3,
                            Text = "Is it a mammal?"
                        },
                        new
                        {
                            Id = 4,
                            Text = "Is it a bird?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
